# -*- coding: utf-8 -*-
"""Level1_task4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NV_Eg3oUy9GwLErVjCin2ngX8fbGyGV8

# Following operation we need to perform ​

* Read an image in RGB format​

* Convert it into grayscale image​

* Invert the image to form the negative image​

* Create a pencil scale image​

# Importing libraries
"""

import cv2  # best module for image task
import matplotlib.pyplot as plt
from google.colab.patches import cv2_imshow

"""# 1 Read The image in RGB format"""

# Load the image in RGB format
image = cv2.imread('image.jpg', cv2.IMREAD_COLOR)
cv2_imshow(image)

"""#2 Convert it into grayscale image​"""

# Convert the image to grayscale
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
cv2_imshow(gray)

"""#3 Invert the image to form the negative image​"""

inverted =  255- gray   #negative image
cv2_imshow(inverted)

"""#4 Create a pencil scale image​"""

# Blur the inverted image
blurred = cv2.GaussianBlur(inverted, (31, 31), 0)  #This helps to smooth out any noise in the image and produce a cleaner pencil sketch effect'''

# Divide the grayscale image by the inverted blurry image
pencil_sketch = cv2.divide(gray, blurred, scale=256)   #We also specify a scale of 256 to ensure that the resulting image is in the correct range of 0-255

"""# Displaying the Image"""

# Display the original and the pencil sketch side by side
fig, ax = plt.subplots(1, 2, figsize=(15, 15))
ax[0].imshow(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))
ax[1].imshow(pencil_sketch, cmap='gray')
plt.show()